{
    "containers": {
        "cna": {
            "affected": [
                {
                    "product": "undertow",
                    "vendor": "RedHat",
                    "versions": [
                        {
                            "status": "affected",
                            "version": "all under 2.0.20"
                        }
                    ]
                }
            ],
            "descriptions": [
                {
                    "lang": "en",
                    "value": "A flaw was found in, all under 2.0.20, in the Undertow DEBUG log for io.undertow.request.security. If enabled, an attacker could abuse this flaw to obtain the user's credentials from the log files."
                }
            ],
            "metrics": [
                {
                    "cvssV3_0": {
                        "attackComplexity": "HIGH",
                        "attackVector": "NETWORK",
                        "availabilityImpact": "NONE",
                        "baseScore": 4.8,
                        "baseSeverity": "MEDIUM",
                        "confidentialityImpact": "HIGH",
                        "integrityImpact": "LOW",
                        "privilegesRequired": "HIGH",
                        "scope": "UNCHANGED",
                        "userInteraction": "REQUIRED",
                        "vectorString": "CVSS:3.0/AV:N/AC:H/PR:H/UI:R/S:U/C:H/I:L/A:N",
                        "version": "3.0"
                    }
                }
            ],
            "problemTypes": [
                {
                    "descriptions": [
                        {
                            "cweId": "CWE-532",
                            "description": "CWE-532",
                            "lang": "en",
                            "type": "CWE"
                        }
                    ]
                }
            ],
            "providerMetadata": {
                "dateUpdated": "2022-02-10T09:06:38",
                "orgId": "53f830b8-0a3f-465b-8143-3b8a9948e749",
                "shortName": "redhat"
            },
            "references": [
                {
                    "tags": [
                        "x_refsource_CONFIRM"
                    ],
                    "url": "https://bugzilla.redhat.com/show_bug.cgi?id=CVE-2019-10212"
                },
                {
                    "name": "RHSA-2019:2998",
                    "tags": [
                        "vendor-advisory",
                        "x_refsource_REDHAT"
                    ],
                    "url": "https://access.redhat.com/errata/RHSA-2019:2998"
                },
                {
                    "name": "RHSA-2020:0727",
                    "tags": [
                        "vendor-advisory",
                        "x_refsource_REDHAT"
                    ],
                    "url": "https://access.redhat.com/errata/RHSA-2020:0727"
                },
                {
                    "tags": [
                        "x_refsource_CONFIRM"
                    ],
                    "url": "https://security.netapp.com/advisory/ntap-20220210-0017/"
                }
            ]
        }
    },
    "cveMetadata": {
        "assignerOrgId": "53f830b8-0a3f-465b-8143-3b8a9948e749",
        "assignerShortName": "redhat",
        "cveId": "CVE-2019-10212",
        "datePublished": "2019-10-02T18:22:08",
        "dateReserved": "2019-03-27T00:00:00",
        "dateUpdated": "2022-02-10T09:06:38",
        "state": "PUBLISHED"
    },
    "dataType": "CVE_RECORD",
    "dataVersion": "5.0"
}
