{
    "containers": {
        "cna": {
            "affected": [
                {
                    "product": "DataPower Gateway",
                    "vendor": "IBM",
                    "versions": [
                        {
                            "status": "affected",
                            "version": "2018.4.1.0"
                        },
                        {
                            "status": "affected",
                            "version": "10.0.1.0"
                        },
                        {
                            "status": "affected",
                            "version": "10.0.1.4"
                        },
                        {
                            "status": "affected",
                            "version": "10.0.2.0"
                        },
                        {
                            "status": "affected",
                            "version": "10.0.3.0"
                        },
                        {
                            "status": "affected",
                            "version": "2018.4.1.17"
                        }
                    ]
                }
            ],
            "datePublic": "2022-05-16T00:00:00",
            "descriptions": [
                {
                    "lang": "en",
                    "value": "IBM DataPower Gateway 10.0.2.0, 10.0.3.0, 10.0.1.0 through 10.0.1.4, and 2018.4.1.0 through 2018.4.1.17 could allow a remote user to cause a denial of service by consuming resources with multiple requests. IBM X-Force ID: 208348."
                }
            ],
            "metrics": [
                {
                    "cvssV3_0": {
                        "attackComplexity": "LOW",
                        "attackVector": "NETWORK",
                        "availabilityImpact": "LOW",
                        "baseScore": 5.3,
                        "baseSeverity": "MEDIUM",
                        "confidentialityImpact": "NONE",
                        "exploitCodeMaturity": "UNPROVEN",
                        "integrityImpact": "NONE",
                        "privilegesRequired": "NONE",
                        "remediationLevel": "OFFICIAL_FIX",
                        "reportConfidence": "CONFIRMED",
                        "scope": "UNCHANGED",
                        "temporalScore": 4.6,
                        "temporalSeverity": "MEDIUM",
                        "userInteraction": "NONE",
                        "vectorString": "CVSS:3.0/PR:N/I:N/C:N/AV:N/A:L/AC:L/UI:N/S:U/RL:O/E:U/RC:C",
                        "version": "3.0"
                    }
                }
            ],
            "problemTypes": [
                {
                    "descriptions": [
                        {
                            "description": "Denial of Service",
                            "lang": "en",
                            "type": "text"
                        }
                    ]
                }
            ],
            "providerMetadata": {
                "dateUpdated": "2022-05-17T16:25:21",
                "orgId": "9a959283-ebb5-44b6-b705-dcc2bbced522",
                "shortName": "ibm"
            },
            "references": [
                {
                    "tags": [
                        "x_refsource_CONFIRM"
                    ],
                    "url": "https://www.ibm.com/support/pages/node/6586704"
                },
                {
                    "name": "ibm-datapower-cve202138872-dos (208348)",
                    "tags": [
                        "vdb-entry",
                        "x_refsource_XF"
                    ],
                    "url": "https://exchange.xforce.ibmcloud.com/vulnerabilities/208348"
                }
            ]
        }
    },
    "cveMetadata": {
        "assignerOrgId": "9a959283-ebb5-44b6-b705-dcc2bbced522",
        "assignerShortName": "ibm",
        "cveId": "CVE-2021-38872",
        "dateReserved": "2021-08-16T00:00:00",
        "dateUpdated": "2022-05-17T16:25:21",
        "state": "PUBLISHED",
        "datePublished": "2022-05-17T16:25:21.862308Z"
    },
    "dataType": "CVE_RECORD",
    "dataVersion": "5.0"
}
