{
    "containers": {
        "cna": {
            "affected": [
                {
                    "product": "Data Risk Manager",
                    "vendor": "IBM",
                    "versions": [
                        {
                            "status": "affected",
                            "version": "2.0.6"
                        }
                    ]
                }
            ],
            "datePublic": "2020-09-21T00:00:00",
            "descriptions": [
                {
                    "lang": "en",
                    "value": "IBM Data Risk Manager (iDNA) 2.0.6 could allow a privileged user to cause a denial of service due to improper input validation. IBM X-Force ID: 184937."
                }
            ],
            "metrics": [
                {
                    "cvssV3_0": {
                        "attackComplexity": "LOW",
                        "attackVector": "NETWORK",
                        "availabilityImpact": "HIGH",
                        "baseScore": 5.5,
                        "baseSeverity": "MEDIUM",
                        "confidentialityImpact": "NONE",
                        "exploitCodeMaturity": "UNPROVEN",
                        "integrityImpact": "LOW",
                        "privilegesRequired": "HIGH",
                        "remediationLevel": "OFFICIAL_FIX",
                        "reportConfidence": "CONFIRMED",
                        "scope": "UNCHANGED",
                        "temporalScore": 4.8,
                        "temporalSeverity": "MEDIUM",
                        "userInteraction": "NONE",
                        "vectorString": "CVSS:3.0/AC:L/C:N/S:U/AV:N/PR:H/I:L/A:H/UI:N/RL:O/E:U/RC:C",
                        "version": "3.0"
                    }
                }
            ],
            "problemTypes": [
                {
                    "descriptions": [
                        {
                            "description": "Denial of Service",
                            "lang": "en",
                            "type": "text"
                        }
                    ]
                }
            ],
            "providerMetadata": {
                "dateUpdated": "2020-09-22T13:55:44",
                "orgId": "9a959283-ebb5-44b6-b705-dcc2bbced522",
                "shortName": "ibm"
            },
            "references": [
                {
                    "tags": [
                        "x_refsource_CONFIRM"
                    ],
                    "url": "https://www.ibm.com/support/pages/node/6335281"
                },
                {
                    "name": "ibm-idna-cve20204618-dos (184937)",
                    "tags": [
                        "vdb-entry",
                        "x_refsource_XF"
                    ],
                    "url": "https://exchange.xforce.ibmcloud.com/vulnerabilities/184937"
                }
            ]
        }
    },
    "cveMetadata": {
        "assignerOrgId": "9a959283-ebb5-44b6-b705-dcc2bbced522",
        "assignerShortName": "ibm",
        "cveId": "CVE-2020-4618",
        "dateReserved": "2019-12-30T00:00:00",
        "dateUpdated": "2020-09-22T13:55:44",
        "state": "PUBLISHED",
        "datePublished": "2020-09-22T13:55:44.424152Z"
    },
    "dataType": "CVE_RECORD",
    "dataVersion": "5.0"
}
