{
    "containers": {
        "cna": {
            "affected": [
                {
                    "product": "python-ecdsa",
                    "vendor": "[UNKNOWN]",
                    "versions": [
                        {
                            "status": "affected",
                            "version": "0.13.3"
                        }
                    ]
                }
            ],
            "descriptions": [
                {
                    "lang": "en",
                    "value": "An error-handling flaw was found in python-ecdsa before version 0.13.3. During signature decoding, malformed DER signatures could raise unexpected exceptions (or no exceptions at all), which could lead to a denial of service."
                }
            ],
            "metrics": [
                {
                    "cvssV3_0": {
                        "attackComplexity": "HIGH",
                        "attackVector": "NETWORK",
                        "availabilityImpact": "LOW",
                        "baseScore": 3.7,
                        "baseSeverity": "LOW",
                        "confidentialityImpact": "NONE",
                        "integrityImpact": "NONE",
                        "privilegesRequired": "NONE",
                        "scope": "UNCHANGED",
                        "userInteraction": "NONE",
                        "vectorString": "CVSS:3.0/AV:N/AC:H/PR:N/UI:N/S:U/C:N/I:N/A:L",
                        "version": "3.0"
                    }
                }
            ],
            "problemTypes": [
                {
                    "descriptions": [
                        {
                            "cweId": "CWE-391",
                            "description": "CWE-391",
                            "lang": "en",
                            "type": "CWE"
                        }
                    ]
                }
            ],
            "providerMetadata": {
                "dateUpdated": "2019-12-18T12:06:05",
                "orgId": "53f830b8-0a3f-465b-8143-3b8a9948e749",
                "shortName": "redhat"
            },
            "references": [
                {
                    "tags": [
                        "x_refsource_CONFIRM"
                    ],
                    "url": "https://bugzilla.redhat.com/show_bug.cgi?id=CVE-2019-14853"
                },
                {
                    "tags": [
                        "x_refsource_MISC"
                    ],
                    "url": "https://github.com/warner/python-ecdsa/releases/tag/python-ecdsa-0.13.3"
                },
                {
                    "name": "DSA-4588",
                    "tags": [
                        "vendor-advisory",
                        "x_refsource_DEBIAN"
                    ],
                    "url": "https://www.debian.org/security/2019/dsa-4588"
                },
                {
                    "name": "20191218 [SECURITY] [DSA 4588-1] python-ecdsa security update",
                    "tags": [
                        "mailing-list",
                        "x_refsource_BUGTRAQ"
                    ],
                    "url": "https://seclists.org/bugtraq/2019/Dec/33"
                }
            ]
        }
    },
    "cveMetadata": {
        "assignerOrgId": "53f830b8-0a3f-465b-8143-3b8a9948e749",
        "assignerShortName": "redhat",
        "cveId": "CVE-2019-14853",
        "datePublished": "2019-11-26T12:06:20",
        "dateReserved": "2019-08-10T00:00:00",
        "dateUpdated": "2019-12-18T12:06:05",
        "state": "PUBLISHED"
    },
    "dataType": "CVE_RECORD",
    "dataVersion": "5.0"
}
